services:
  wanderer_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  wanderer:
    image: wandererltd/community-edition:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - wanderer_db
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - wanderer-conf.env

volumes:
  db-data:
    driver: local
